[package]
name = "runltp-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version = "2.34.0", features = ["yaml"]}
chrono = "0.4.19"
git2 = "0.13.25"
os_info = "3.0.9"